import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import Header from "@/components/Header/Header";
import { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server"; // <-- ИМПОРТИРУЕМ setRequestLocale
import { routing } from "@/src/i18n/routing";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
  display: "swap",
});

type Props = {
  children: ReactNode;
  params: { locale: string };
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Props) {
  setRequestLocale(locale);

  let messages;
  try {
    messages = await getMessages();
  } catch (error) {
    console.error(`Failed to load messages for locale ${locale}:`, error);

    messages = await (
      await import(
        `../../../messages/${routing.defaultLocale}/${routing.defaultLocale}.json`
      )
    ).default;
  }

  return (
    <html lang={locale}>
      <body className={roboto.variable}>
        <TanStackProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header currentLocale={locale} />
            <main>{children}</main>
            <Footer />
          </NextIntlClientProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
